Remove thor
SwissLife-OSS/HotChocolate.Extensions pull request #24
Opened 2022-11-25 15:14 UTC by gmiserez

Removes all thor references.

Translations: 
- An observer class will be added later to let the user of the package handle the logging himself (#22)

Tracking:
- TBD

2022-11-28 07:57 UTC, glucaci requested changes

2022-11-28 09:55 UTC, gmiserez commented
Added implementation of Observer class (enhancement #22)

2022-11-28 09:57 UTC, gmiserez commented on src/HotChocolate.Extensions.Tracking/Persistence/TrackingHostedService.cs
> +            _logger.LogInformation("Saving tracking message", message.TrackingEntry);
good point.

2022-11-28 09:57 UTC, gmiserez commented on src/HotChocolate.Extensions.Tracking/Persistence/TrackingHostedService.cs
>          await foreach (TrackingMessage message in ReadAllAsync(stoppingToken))
Good point. Done.

2022-11-28 09:57 UTC, gmiserez commented on src/HotChocolate.Extensions.Tracking/Persistence/TrackingHostedService.cs
>          _trackingRepositoryFactory = trackingRepositoryFactory;
Done.

2022-11-28 09:59 UTC, gmiserez commented on src/HotChocolate.Extensions.Translation/Resources/ResourceClientExtensions.cs
> -            TranslationEventSource.Log.ResourceMissing(key);
Implemented the Observer class Feature from enhancement #22 instead. Now a `OnMissingResource` Method of the observer class gets invoked every time a resource is missing. Users can add their own implementation of the `TranslationObserver` to the DI

2022-11-28 10:01 UTC, gmiserez commented on src/HotChocolate.Extensions.Tracking/Persistence/TrackingHostedService.cs
> +        _logger.LogWarning("Tracking Pipeline Started");
Done.

2022-11-28 10:13 UTC, gmiserez commented on src/HotChocolate.Extensions.Tracking/Persistence/TrackingHostedService.cs
>      {
done.

2022-11-28 15:49 UTC, glucaci commented
/azp run

2022-11-29 09:33 UTC, glucaci approved these changes

2022-11-29 09:38 UTC, merged